import type {Metadata} from "next";
import {Raleway, Rubik} from "next/font/google";
import "./globals.css";
import "./reset.css";
import React from "react";

const rubik = Rubik({
  subsets: ["latin"],
  variable: '--font-rubik'
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: '--font-raleway'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${rubik.variable} ${raleway.variable}`}>
    <body>{children}</body>
    </html>
  );
}
